// Mark this class as an Injectable service, available project-wide
import { Injectable } from '@angular/core';

// Import AngularFire modules for Realtime Database interaction
import { AngularFireDatabase, AngularFireList, AngularFireObject  } from '@angular/fire/compat/database';

// Import our IExpense data interface
import { IExpense } from '../models/common.model';

@Injectable({
  providedIn: 'root' // Singleton: One instance of this service for the entire app
})
export class ExpenseService {
  // Define the base path for our expenses collection in the database
  private dbPath = '/expenses';
  
  // Reference to the list of expenses in Firebase
  expensesRef: AngularFireList<IExpense>;

  // Inject AngularFireDatabase to perform operations
  constructor(private db: AngularFireDatabase) {
    // Initialize the list reference pointing to the '/expenses' path
    this.expensesRef = db.list(this.dbPath)
  }

  /**
   * Retrieves the entire list reference from Firebase
   * Used with .snapshotChanges() for real-time observable streams
   */
  getAllExpenses() {
    return this.expensesRef;
  }

  /**
   * Retrieves a single specific expense object for viewing or editing
   * @param key The unique ID generated by Firebase
   */
  getExpense(key: string): AngularFireObject<IExpense> {
    return this.db.object(`${this.dbPath}/${key}`);
  }

  /**
   * Pushes a new expense into the Firebase list
   * @param expense The data object to create
   */
  addExpense(expense: IExpense) {
    this.expensesRef.push(expense);
  }

  /**
   * Updates an existing expense's fields without overwriting the entire object
   * @param key Unique ID of the item
   * @param expense The updated data
   */
  updateExpense(key: string, expense: IExpense) {
    this.expensesRef.update(key, expense);
  }

  /**
   * Removes a specific item from the database
   * @param key Unique ID of the item to delete
   */
  deleteExpense(key: string) {
    return this.expensesRef.remove(key);
  }
}
